{
 "title": "Hitachi Dashboard",
 "tags": [ "hitachi" ],
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "influxdb" },
   {
    "name": "storageSystemId",
    "label": "Storage Serial",
    "query": "SHOW TAG VALUES WITH KEY=\"storageSystemId\""
   },
   {
    "name": "Owner",
    "label": "Owner",
    "query": "SHOW TAG VALUES WITH  KEY=\"owner\" WHERE \"storageSystemId\" =~ /^$storageSystemId$/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\r\n  background-color: hsl(0, 100%, 50%);  /* Pure red background */\r\n  width: 100%;\r\n  height: 100%;\r\n  display: flex;\r\n  justify-content: center;\r\n  align-items: center;\r\n\">\r\n  <span style=\"\r\n    color: hsl(0, 0%, 100%);              /* Pure white text */\r\n    font-size: 50px;\r\n  \">\r\n    <strong>Hitachi Vantara</strong>\r\n  </span>\r\n</div>\r\n\r\n#    \r\n# \r\n# Storages  (${storageSystemId})"
   }
  },
  {
   "title": "Total Response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvResponseTime.1",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total IOPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvIops.1",
     "select": [
      [
       { "params": [ "totalIOPS" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Transfer Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "select": [
      [
       { "params": [ "transferRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Storage IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readIOPS" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeIOPS" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       { "params": [ "totalIOPS" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Sequential IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "seqReadIOPS" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "seqWriteIOPS" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Random IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "randomReadIOPS" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "randomWriteIOPS" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Storage Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readTransRate" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeTransRate" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       { "params": [ "transferRate" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Transfer Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readTransRate" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "writeTransRate" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Seq Transfer Rate",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "seqReadTransRate" ], "type": "field" },
       { "params": [ "Seq Read" ], "type": "alias" }
      ],
      [
       { "params": [ "seqWriteTransRate" ], "type": "field" },
       { "params": [ "Seq Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Seq/Random Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "randomReadTransRate" ], "type": "field" },
       { "params": [ "Ran Read" ], "type": "alias" }
      ],
      [
       { "params": [ "randomWriteTransRate" ], "type": "field" },
       { "params": [ "Ran Write" ], "type": "alias" }
      ],
      [
       { "params": [ "seqReadTransRate" ], "type": "field" },
       { "params": [ "Seq Read" ], "type": "alias" }
      ],
      [
       { "params": [ "seqWriteTransRate" ], "type": "field" },
       { "params": [ "Seq Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Random Transfer Rate",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "randomReadTransRate" ], "type": "field" },
       { "params": [ "Ran Read" ], "type": "alias" }
      ],
      [
       { "params": [ "randomWriteTransRate" ], "type": "field" },
       { "params": [ "Ran Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Storage Response Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvResponseTime.1",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       { "params": [ "Read Response" ], "type": "alias" }
      ],
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       { "params": [ "Write Response" ], "type": "alias" }
      ],
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "Total Response" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Response Time Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvResponseTime.1",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" },
       { "params": [ "Read Response" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Response Time Avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvResponseTime.1",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" },
       { "params": [ "Write Response" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">\r\n\r\n# Processor"
   }
  },
  {
   "title": "MP Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_storageSystemId",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvMpUtilization.1",
     "query": "SELECT mean(\"value\") FROM \"hvMpUtilization.1\" ",
     "select": [
      [
       { "params": [ "utilization" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 81 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  { "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">\r\n\r\n# Port"
   }
  },
  {
   "title": "Port Response Time",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "port::tag" ], "type": "tag" }
     ],
     "measurement": "hvPortResponse.1",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 105 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Port Transfer Rate",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "port::tag" ], "type": "tag" }
     ],
     "measurement": "hvPortTransferRate.1",
     "query": "SELECT \"transferRate\" FROM \"hvPortTransfer.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/ AND \"transferRate\" > 0) AND $timeFilter GROUP BY \"port\"::tag",
     "select": [
      [
       { "params": [ "transferRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "transferRate", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 119 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Port IOPS >10K",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_port",
     "groupBy": [
      { "params": [ "port::tag" ], "type": "tag" }
     ],
     "measurement": "hvPortIops.1",
     "query": "SELECT \"port\", LAST(\"totalIOPS\") AS \"totalIOPS\" FROM \"hvPortIOPS.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/ AND \"totalIOPS\"::field > 0) AND $timeFilter GROUP BY \"port\"::tag LIMIT 10",
     "select": [
      [
       { "params": [ "totalIOPS" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "totalIOPS::field", "operator": ">", "value": "10000" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 129 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">\r\n\r\n# Cache"
   }
  },
  {
   "title": "Storage Cache (Write Pending Rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvCache.1",
     "select": [
      [
       { "params": [ "writePendingRate" ], "type": "field" },
       { "params": [ "Write Pending" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 139 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "MPB Cache (Write Pending Rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" },
      { "params": [ "mpb::tag" ], "type": "tag" }
     ],
     "measurement": "hvMpbCache.1",
     "select": [
      [
       { "params": [ "writePendingRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 148 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Block Size (Seq-Random)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvBlockSizeSR.1",
     "query": "SELECT mean(\"value\") FROM \"hvMpbUtilization.1\" ",
     "select": [
      [
       { "params": [ "RandomBlockSize" ], "type": "field" },
       { "params": [ "Random" ], "type": "alias" }
      ],
      [
       { "params": [ "SeqBlockSize" ], "type": "field" },
       { "params": [ "Sequential" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "title": "Block Size (Read-Write)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvBlockSizeRW.1",
     "select": [
      [
       { "params": [ "writeKBPIO" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       { "params": [ "readKBPIO" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 159 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Pool Capacity (By Time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "$col ($tag_storageSystemId)",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvPools.2",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "availableCapacityInBytes" ], "type": "field" },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "capacityInBytes" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "usedCapacityInBytes" ], "type": "field" },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 170 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Pool Capacity (Last)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "storagePoolId::tag" ], "type": "tag" }
     ],
     "measurement": "hvPools.2",
     "query": "SELECT \n  floor(last(\"availableCapacityInBytes\") / 1024 + 0.5) AS \"Free\", \n  floor(\"capacityInBytes\" / 1024 + 0.5) AS \"Total\", \n  floor(\"usedCapacityInBytes\" / 1024 + 0.5) AS \"Used\" \nFROM \"hvPools.2\" \nWHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) \nAND $timeFilter \nGROUP BY \"storageSystemId\"::tag, \"storagePoolId\"::tag",
     "select": [
      [
       { "params": [ "availableCapacityInBytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "capacityInBytes" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "usedCapacityInBytes" ], "type": "field" },
       { "params": [ "Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 181 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Storage Health (Alerts)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvStorageHealth.1",
     "select": [
      [
       { "params": [ "batteryAlerts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Battery" ], "type": "alias" }
      ],
      [
       { "params": [ "cacheAlerts" ], "type": "field" },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "diskAlerts" ], "type": "field" },
       { "params": [ "Disk" ], "type": "alias" }
      ],
      [
       { "params": [ "fanAlerts" ], "type": "field" },
       { "params": [ "Fan" ], "type": "alias" }
      ],
      [
       { "params": [ "memoryAlerts" ], "type": "field" },
       { "params": [ "Memory" ], "type": "alias" }
      ],
      [
       { "params": [ "portAlerts" ], "type": "field" },
       { "params": [ "Port" ], "type": "alias" }
      ],
      [
       { "params": [ "powerSupplyAlerts" ], "type": "field" },
       { "params": [ "Power Supply" ], "type": "alias" }
      ],
      [
       { "params": [ "processorAlerts" ], "type": "field" },
       { "params": [ "Processor" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 188 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Storage Info ",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvStorages.1",
     "select": [
      [
       { "params": [ "storageSystemName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Storage Name" ], "type": "alias" }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "firmwareVersion" ], "type": "field" },
       { "params": [ "Firmware" ], "type": "alias" }
      ],
      [
       { "params": [ "svpIpAddress" ], "type": "field" },
       { "params": [ "SVP IP" ], "type": "alias" }
      ],
      [
       { "params": [ "gum1IpAddress" ], "type": "field" },
       { "params": [ "Controller 1" ], "type": "alias" }
      ],
      [
       { "params": [ "gum2IpAddress" ], "type": "field" },
       { "params": [ "Controller 2" ], "type": "alias" }
      ],
      [
       { "params": [ "horcmVersion" ], "type": "field" },
       { "params": [ "Horcm CLI" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 195 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Parity Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "parityGroupId::tag" ], "type": "tag" }
     ],
     "measurement": "hvParityGroups.1",
     "select": [
      [
       { "params": [ "raidLayout" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Raid Layout" ], "type": "alias" }
      ],
      [
       { "params": [ "raidLevel" ], "type": "field" },
       { "params": [ "Raid Type" ], "type": "alias" }
      ],
      [
       { "params": [ "diskSpec.type" ], "type": "field" },
       { "params": [ "Disk Type" ], "type": "alias" }
      ],
      [
       { "params": [ "encryption" ], "type": "field" },
       { "params": [ "Encrypted" ], "type": "alias" }
      ],
      [
       { "params": [ "compression" ], "type": "field" },
       { "params": [ "Compression" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 205 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Pool Info ",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvPools.1",
     "select": [
      [
       { "params": [ "label" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Pool Name" ], "type": "alias" }
      ],
      [
       { "params": [ "status" ], "type": "field" },
       { "params": [ "Status" ], "type": "alias" }
      ],
      [
       { "params": [ "deduplicationEnabled" ], "type": "field" },
       { "params": [ "Dedup Enable" ], "type": "alias" }
      ],
      [
       { "params": [ "encrypted" ], "type": "field" },
       { "params": [ "Encryption" ], "type": "alias" }
      ],
      [
       { "params": [ "fmcCompressed" ], "type": "field" },
       { "params": [ "FMD Compression" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 213 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Pool Saving",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" }
     ],
     "measurement": "hvPools.4",
     "select": [
      [
       { "params": [ "totalSoftwareSavingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total Saving" ], "type": "alias" }
      ],
      [
       { "params": [ "compressionRate" ], "type": "field" },
       { "params": [ "compression" ], "type": "alias" }
      ],
      [
       { "params": [ "deduplicationRate" ], "type": "field" },
       { "params": [ "Deduplication" ], "type": "alias" }
      ],
      [
       { "params": [ "patternMatchingRate" ], "type": "field" },
       { "params": [ "Pattern Matching" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 223 },
   "options": {
    "content": "# Host Groups (Owner)\r\n<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Total Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transferRate" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 240 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Read Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readTransRate" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "title": "Owner Write Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerTransferRate.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "writeTransRate" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 255 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 257 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalIOPS" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 270 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 272 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readIOPS" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "title": "Owner Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 272 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerIops.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "writeIOPS" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 284 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Total Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerResponseTime.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "responseTime" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 296 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Read Response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 298 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerResponseTime.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "readResponseTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 307 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "Owner Write Response",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 309 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_owner",
     "groupBy": [
      { "params": [ "storageSystemId::tag" ], "type": "tag" },
      { "params": [ "owner::tag" ], "type": "tag" }
     ],
     "measurement": "hvOwnerResponseTime.1",
     "query": "SELECT \"seqReadIOPS\" FROM \"hvIops.1\" WHERE (\"storageSystemId\"::tag =~ /^$storageSystemId$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "writeResponseTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "storageSystemId::tag", "operator": "=~", "value": "/^$storageSystemId$/" },
      { "condition": "AND", "key": "owner::tag", "operator": "=~", "value": "/^$Owner$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 319 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #00ffff\">"
   }
  },
  {
   "title": "HUR DELTA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageSystemId" ], "type": "tag" }
     ],
     "measurement": "hvHurDelta.1",
     "select": [
      [
       { "params": [ "delta" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}