{
 "title": "Hitachi VSP One Block",
 "description": "Sample Dashboard for Ops Center Analyzer Adapter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "Storage",
    "query": "SHOW TAG VALUES FROM \"storage\" WITH KEY = \"instance_name\" WHERE $timeFilter"
   },
   {
    "name": "Processor",
    "query": "SHOW TAG VALUES FROM \"storage_processor\" WITH KEY =\"processor_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Cache",
    "query": "SHOW TAG VALUES FROM \"storage_cache_per_processor\" WITH KEY =\"cache_number\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Port",
    "query": "SHOW TAG VALUES FROM \"storage_port\" WITH KEY =\"port_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Pool",
    "query": "SHOW TAG VALUES FROM \"storage_pool\" WITH KEY =\"pool_display_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Volume",
    "query": "SHOW TAG VALUES FROM \"storage_ldev\" WITH KEY =\"ldev_number\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "worst_iops_pool",
    "query": "SELECT\n    \"pool_display_name\"\nFROM\n    (\n        SELECT\n            \"pool_display_name\",\n            top(\"max_total_total_iops\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"sum_of_total_io_per_sec\") as \"max_total_total_iops\"\n                FROM\n                    \"storage_pool\"\n                WHERE\n                    $timeFilter\n                    AND instance_name =~ /$Storage/\n                    AND pool_display_name =~ /$Pool/\n                GROUP BY\n                    \"instance_name\",\n                    \"pool_display_name\"\n            )\n    )"
   },
   {
    "name": "worst_avg_xfer_port",
    "query": "SELECT\n    \"port_name\"\nFROM\n(\n        SELECT\n            \"port_name\",\n            top(\"worst_xfer_rate\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"avg_of_transfer_mebibytes_per_sec\") as \"worst_xfer_rate\"\n                FROM\n                    \"storage_port\"\n                WHERE\n                    $timeFilter\n                    AND \"instance_name\" =~ /^$Storage$/\n                    AND \"port_name\" =~ /^$Port$/\n                GROUP BY\n                    \"instance_name\",\n                    \"port_name\"\n            )\n    )"
   },
   {
    "name": "worst_usage_pool",
    "query": "SELECT\n    \"pool_display_name\"\nFROM\n    (\n        SELECT\n            \"pool_display_name\",\n            top(\"max_physical_usage_percent\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"physical_usage_in_percent\") as \"max_physical_usage_percent\"\n                FROM\n                    (\n                        SELECT\n                            \"physical_usage_in_gibibyte\" / \"total_physical_capacity_in_gibibyte\" * 100 as \"physical_usage_in_percent\"\n                        FROM\n                            \"storage_pool\"\n                        )\n                WHERE\n                    $timeFilter\n                    AND instance_name =~ /$Storage/\n                    AND pool_display_name =~ /$Pool/\n                GROUP BY\n                    \"instance_name\",\n                    \"pool_display_name\"\n            )\n    )"
   },
   { "name": "top_count", "label": "Top count to display", "query": "10, 20, 30, 40, 50, 100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ${__dashboard}\n\nSample Dashboard for Ops Center Analyzer Adapter"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "## All Storage Systems Report\n\nCompare all storage systems"
   }
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "description": "Total IOPS per storage system",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Average response time per storage system",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    max(\"avg_of_response_time_in_micro_sec\")\nFROM(\n        SELECT\n            (\"avg_of_read_response_time_in_micro_sec\" + \"avg_of_write_response_time_in_micro_sec\") / 2 AS \"avg_of_response_time_in_micro_sec\"\n        FROM\n            \"storage\"\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "description": "Total transfer rate per storage system",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "description": "Total pool usage per storage system",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"sum_of_pool_physical_usage_in_percent\") AS \"Total Pool Usage\"\nFROM\n    (\n        SELECT\n            \"sum_of_pool_physical_usage_in_gibibyte\" / \"sum_of_pool_total_physical_capacity_in_gibibyte\" * 100 AS \"sum_of_pool_physical_usage_in_percent\"\n        FROM\n            \"storage\"\n        )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "## Selected Storage System Report\n\nAnalyze resources of the selected storage system (${Storage})"
   }
  },
  { "title": "Storage System ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"avg_of_read_response_time_in_micro_sec\") AS \"Average Read Response Time\", max(\"avg_of_write_response_time_in_micro_sec\") AS \"Average Write Response Time\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Average Read Response Time" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Average Write Response Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"sum_of_pool_physical_usage_in_percent\") AS \"Total Pool Usage\"\nFROM\n    (\n        SELECT\n            \"sum_of_pool_physical_usage_in_gibibyte\" / \"sum_of_pool_total_physical_capacity_in_gibibyte\" * 100 AS \"sum_of_pool_physical_usage_in_percent\"\n        FROM\n            \"storage\"\n        )\nWHERE\n        $timeFilter\n        AND \"instance_name\"::tag =~ /^$Storage$/\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors, Caches and Ports in $Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Processor Busy Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_processor_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_processor",
     "query": "SELECT max(\"busy_rate_in_percent\") AS \"Busy Rate\" FROM \"storage_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "busy_rate_in_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Busy Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Write Pending Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Processor: $tag_processor_name, Cache: CLPR$tag_cache_number",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "cache_number::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_cache_per_processor",
     "query": "SELECT max(\"cache_write_pending_in_percent\") AS \"Cache Write Pending Rate\" FROM \"storage_cache_per_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/ AND \"cache_number\"::tag =~ /^$Cache$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag, \"cache_number\"::tag fill(none)",
     "select": [
      [
       { "params": [ "cache_write_pending_in_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Cache Write Pending Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" },
      { "condition": "AND", "key": "cache_number::tag", "operator": "=~", "value": "/^$Cache$/" }
     ]
    }
   ]
  },
  {
   "title": "Port Transfer Rate (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$tag_port_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "port_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_port",
     "query": "SELECT max(\"peak_of_transfer_mebibytes_per_sec\") AS \"Peak Transfer Rate\" FROM \"storage_port\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"port_name\"::tag =~ /^$worst_avg_xfer_port$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"port_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "peak_of_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Peak Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "port_name::tag", "operator": "=~", "value": "/^$worst_avg_xfer_port$/" }
     ]
    }
   ]
  },
  { "title": "Pools in $Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pool Capacity",
   "type": "timeseries",
   "description": "Sum of capacity of the selected pools",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    max(\"total_physical_total_capacity_in_gbytes\") as \"Phys. Total\",\n    max(\"total_subscription_capacity_in_gbytes\") as \"Subscription\",\n    max(\"total_physical_used_capacity_in_gbytes\") as \"Phys. Used\"\nFROM\n(\n        SELECT\n            sum(\"subscribed_capacity_in_gibibyte\") as \"total_subscription_capacity_in_gbytes\",\n            sum(\"physical_usage_in_gibibyte\") as \"total_physical_used_capacity_in_gbytes\",\n            sum(\"total_physical_capacity_in_gibibyte\") as \"total_physical_total_capacity_in_gbytes\"\n        FROM\n            \"storage_pool\"\n        WHERE\n            \"instance_name\" =~ /^$Storage$/\n            AND \"pool_display_name\" =~ /^$Pool$/\n        GROUP BY\n            \"instance_name\"\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval)\nfill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_pool_total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_pool_subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_pool_physical_usage_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_pool_display_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"physical_usage_in_percent\") AS \"Pool Usage\"\nFROM\n    (\n        SELECT\n            \"physical_usage_in_gibibyte\" / \"total_physical_capacity_in_gibibyte\" * 100 as \"physical_usage_in_percent\"\n        FROM\n            \"storage_pool\"\n        )\nWHERE\n    \"instance_name\"::tag =~ /^$Storage$/\n    AND \"pool_display_name\"::tag =~ /^$worst_usage_pool$/\n    AND $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag,\n    \"pool_display_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": " IOPS (All Pools)",
   "type": "table",
   "description": "Average IOPS during the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_pool_display_name",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT mean(\"sum_of_total_io_per_sec\") AS \"Total\", mean(\"sum_of_read_io_per_sec\") AS \"Read\", mean(\"sum_of_write_io_per_sec\") AS \"Write\" FROM \"storage_pool\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"pool_display_name\"::tag =~ /^$worst_usage_pool$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"pool_display_name\"::tag",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool IOPS (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col ($tag_pool_display_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total\" FROM \"storage_pool\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"pool_display_name\"::tag =~ /^$worst_iops_pool$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"pool_display_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$worst_iops_pool$/" }
     ]
    }
   ]
  },
  { "title": "Volumes in $Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "IOPS (All Volumes)",
   "type": "table",
   "description": "Average IOPS during the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT\n    mean(\"total_io_per_sec\") AS \"Total\",\n    mean(\"read_io_per_sec\") AS \"Read\",\n    mean(\"write_io_per_sec\") AS \"Write\"   \nFROM\n    (\n        SELECT\n            (\"read_io_per_sec\" + \"write_io_per_sec\") AS \"total_io_per_sec\", \n            \"read_io_per_sec\",\n            \"write_io_per_sec\"\n        FROM\n            \"storage_ldev\"\n        WHERE\n            \"instance_name\"::tag =~ /^$Storage$/\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    \"instance_name\"::tag,\n    \"ldev_number\"::tag",
     "select": [
      [
       { "params": [ "read_io_per_sec" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_io_per_sec" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume IOPS",
   "type": "timeseries",
   "description": "IOPS of the selected volumes",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col ($tag_ldev_number)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT\n    max(\"total_io_per_sec\") AS \"Total\"\nFROM\n    (\n        SELECT\n            \"read_io_per_sec\" + \"write_io_per_sec\" AS \"total_io_per_sec\"\n        FROM\n            \"storage_ldev\"\n        WHERE\n            \"instance_name\"::tag =~ /^$Storage$/\n            AND \"ldev_number\"::tag =~ /^$Volume$/\n            AND $timeFilter\n        )\nWHERE $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag,\n    \"ldev_number\"::tag\nfill(none)",
     "select": [
      [
       { "params": [ "read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time (All Volumes)",
   "type": "table",
   "description": "Average response time during the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT mean(\"read_response_time_in_micro_sec\") AS \"Read\", mean(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"ldev_number\"::tag",
     "select": [
      [
       {
        "params": [
         "read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume Response Time",
   "type": "timeseries",
   "description": "Response time of the selected volumes",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col ($tag_ldev_number)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT max(\"read_response_time_in_micro_sec\") AS \"Read\", max(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"ldev_number\"::tag =~ /^$Volume$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"ldev_number\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  }
 ]
}