{
 "title": "Hitachi Vantara",
 "description": "Dashboard for Ops Center Analyzer Adapter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "Storage",
    "query": "SHOW TAG VALUES FROM \"storage\" WITH KEY = \"instance_name\" WHERE $timeFilter"
   },
   {
    "name": "Host_Group",
    "query": {
     "query": "SHOW TAG VALUES FROM \"storage_ldev\" WITH KEY =\"associated_host_groups\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
    }
   },
   {
    "name": "Processor",
    "query": {
     "query": "SHOW TAG VALUES FROM \"storage_processor\" WITH KEY =\"processor_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
    }
   },
   {
    "name": "Cache",
    "query": "SHOW TAG VALUES FROM \"storage_cache_per_processor\" WITH KEY =\"cache_number\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Port",
    "query": "SHOW TAG VALUES FROM \"storage_port\" WITH KEY =\"port_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Pool",
    "query": "SHOW TAG VALUES FROM \"storage_pool\" WITH KEY =\"pool_display_name\" WHERE \"instance_name\" =~ /^${Storage}$/ AND $timeFilter"
   },
   {
    "name": "Volume",
    "query": {
     "query": "SHOW TAG VALUES FROM \"storage_ldev\" WITH KEY =\"ldev_number\" WHERE \"instance_name\" =~ /^${Storage}$/ AND \"associated_host_groups\" =~ /^${Host_Group}$/"
    }
   },
   {
    "name": "worst_iops_pool",
    "query": "SELECT\n    \"pool_display_name\"\nFROM\n    (\n        SELECT\n            \"pool_display_name\",\n            top(\"max_total_total_iops\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"sum_of_total_io_per_sec\") as \"max_total_total_iops\"\n                FROM\n                    \"storage_pool\"\n                WHERE\n                    $timeFilter\n                    AND instance_name =~ /$Storage/\n                    AND pool_display_name =~ /$Pool/\n                GROUP BY\n                    \"instance_name\",\n                    \"pool_display_name\"\n            )\n    )"
   },
   {
    "name": "worst_avg_xfer_port",
    "query": "SELECT\n    \"port_name\"\nFROM\n(\n        SELECT\n            \"port_name\",\n            top(\"worst_xfer_rate\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"avg_of_transfer_mebibytes_per_sec\") as \"worst_xfer_rate\"\n                FROM\n                    \"storage_port\"\n                WHERE\n                    $timeFilter\n                    AND \"instance_name\" =~ /^$Storage$/\n                    AND \"port_name\" =~ /^$Port$/\n                GROUP BY\n                    \"instance_name\",\n                    \"port_name\"\n            )\n    )"
   },
   {
    "name": "worst_avg_io_port",
    "query": {
     "query": "SELECT\n    \"port_name\"\nFROM\n(\n        SELECT\n            \"port_name\",\n            top(\"worst_io_rate\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"avg_of_total_io_per_sec\") as \"worst_io_rate\"\n                FROM\n                    \"storage_port\"\n                WHERE\n                    $timeFilter\n                    AND \"instance_name\" =~ /^$Storage$/\n                    AND \"port_name\" =~ /^$Port$/\n                GROUP BY\n                    \"instance_name\",\n                    \"port_name\"\n            )\n    )"
    }
   },
   {
    "name": "worst_usage_pool",
    "query": "SELECT\n    \"pool_display_name\"\nFROM\n    (\n        SELECT\n            \"pool_display_name\",\n            top(\"max_physical_usage_percent\", $top_count)\n        FROM\n            (\n                SELECT\n                    max(\"physical_usage_in_percent\") as \"max_physical_usage_percent\"\n                FROM\n                    (\n                        SELECT\n                            \"physical_usage_in_gibibyte\" / \"total_physical_capacity_in_gibibyte\" * 100 as \"physical_usage_in_percent\"\n                        FROM\n                            \"storage_pool\"\n                        )\n                WHERE\n                    $timeFilter\n                    AND instance_name =~ /$Storage/\n                    AND pool_display_name =~ /$Pool/\n                GROUP BY\n                    \"instance_name\",\n                    \"pool_display_name\"\n            )\n    )"
   },
   { "name": "top_count", "label": "Top count to display", "query": "10, 20, 30, 40, 50, 100" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\r\n  background-color: hsl(0, 100%, 50%);  /* Pure red background */\r\n  width: 100%;\r\n  height: 100%;\r\n  display: flex;\r\n  justify-content: center;\r\n  align-items: center;\r\n\">\r\n  <span style=\"\r\n    color: hsl(0, 0%, 100%);              /* Pure white text */\r\n    font-size: 70px;\r\n  \">\r\n    <strong>Hitachi Vantara</strong>\r\n  </span>\r\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "## All Storage Systems Report\n\nCompare all storage systems"
   }
  },
  { "title": "All Storages Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IOPS",
   "type": "gauge",
   "description": "Total IOPS per storage system",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "description": "Average response time per storage system",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    max(\"avg_of_response_time_in_micro_sec\")\nFROM(\n        SELECT\n            (\"avg_of_read_response_time_in_micro_sec\" + \"avg_of_write_response_time_in_micro_sec\") / 2 AS \"avg_of_response_time_in_micro_sec\"\n        FROM\n            \"storage\"\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "gauge",
   "description": "Total transfer rate per storage system",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<hr style=\"height: 2px; background-color: #4acdeb\">"
   }
  },
  {
   "title": "Total IOPS",
   "type": "timeseries",
   "description": "Total IOPS per storage system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Average response time per storage system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    max(\"avg_of_response_time_in_micro_sec\")\nFROM(\n        SELECT\n            (\"avg_of_read_response_time_in_micro_sec\" + \"avg_of_write_response_time_in_micro_sec\") / 2 AS \"avg_of_response_time_in_micro_sec\"\n        FROM\n            \"storage\"\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<hr style=\"height: 2px; background-color: #4acdeb\">"
   }
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "description": "Total transfer rate per storage system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "description": "Total pool usage per storage system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"sum_of_pool_physical_usage_in_percent\") AS \"Total Pool Usage\"\nFROM\n    (\n        SELECT\n            \"sum_of_pool_physical_usage_in_gibibyte\" / \"sum_of_pool_total_physical_capacity_in_gibibyte\" * 100 AS \"sum_of_pool_physical_usage_in_percent\"\n        FROM\n            \"storage\"\n        )\nWHERE\n    $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<hr style=\"height: 15px; background-color: #b00000\">"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "## Selected Storage System Report\n\nAnalyze resources of the selected storage system"
   }
  },
  {
   "title": "Storage I/O,Response,Transfer Rate ($Storage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "options": { "content": "#### IOPS (${Storage})\n\n" } },
  {
   "title": "Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Total IOPS Avg",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<hr style=\"height: 2px; background-color: #4acdeb\">"
   }
  },
  {
   "title": "Seq IOPS",
   "type": "piechart",
   "description": "Seq IOPS",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_sequential_read_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Seq/Random IOPS",
   "type": "timeseries",
   "description": "Seq/Random IOPS",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$col($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_random_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rand Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_random_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rand Write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_read_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Seq Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Seq Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Rand IOPS",
   "type": "piechart",
   "description": "Rand IOPS",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total IOPS\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_random_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Ran Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_random_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Ran Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 66 },
   "options": {
    "content": "#### Transfer Rate (${Storage})\n\n"
   }
  },
  {
   "title": "Total Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Transfer Rate Avg",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<hr style=\"height: 2px; background-color: #4acdeb\">"
   }
  },
  {
   "title": "Seq Transfer Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col($tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_sequential_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Read " ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Read " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Seq/Rand Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$col($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_random_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Rand Read " ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_random_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Rand Write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Read " ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Seq Read " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Rand Transfer Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col($tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"sum_of_total_transfer_mebibytes_per_sec\") AS \"Total Transfer Rate\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_random_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Rand Read " ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_random_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Rand Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
   "options": {
    "content": "#### Response Time (${Storage})\n\n"
   }
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"avg_of_read_response_time_in_micro_sec\") AS \"Average Read Response Time\", max(\"avg_of_write_response_time_in_micro_sec\") AS \"Average Write Response Time\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Response Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"avg_of_read_response_time_in_micro_sec\") AS \"Average Read Response Time\", max(\"avg_of_write_response_time_in_micro_sec\") AS \"Average Write Response Time\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Response Avg",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT max(\"avg_of_read_response_time_in_micro_sec\") AS \"Average Read Response Time\", max(\"avg_of_write_response_time_in_micro_sec\") AS \"Average Write Response Time\" FROM \"storage\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "avg_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Avg Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  { "title": "Processor ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Processor Utilization",
   "type": "timeseries",
   "description": "Yellow Line -> Warning / Red Line -> Critical Limits",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_processor_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_processor",
     "query": "SELECT max(\"busy_rate_in_percent\") AS \"Busy Rate\" FROM \"storage_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "busy_rate_in_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Busy Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 111 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Processor Busy Rate",
   "type": "gauge",
   "description": "Yellow 70-85 / \nRed > 85",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_processor_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_processor",
     "query": "SELECT max(\"busy_rate_in_percent\") AS \"Busy Rate\" FROM \"storage_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "busy_rate_in_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Busy Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 121 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Processor Total IOPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_processor_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_processor",
     "query": "SELECT max(\"busy_rate_in_percent\") AS \"Busy Rate\" FROM \"storage_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Busy Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 131 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Cache Write Pending Rate",
   "type": "timeseries",
   "description": "Yellow line --> warning / Red line --> Critical",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_processor_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "processor_name::tag" ], "type": "tag" },
      { "params": [ "cache_number::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_cache_per_processor",
     "query": "SELECT max(\"cache_write_pending_in_percent\") AS \"Cache Write Pending Rate\" FROM \"storage_cache_per_processor\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"processor_name\"::tag =~ /^$Processor$/ AND \"cache_number\"::tag =~ /^$Cache$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"processor_name\"::tag, \"cache_number\"::tag fill(none)",
     "select": [
      [
       { "params": [ "cache_write_pending_in_percent" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Cache Write Pending Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "processor_name::tag", "operator": "=~", "value": "/^$Processor$/" },
      { "condition": "AND", "key": "cache_number::tag", "operator": "=~", "value": "/^$Cache$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 141 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  { "title": "Ports ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Port Transfer Rate (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "alias": "$tag_port_name($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "port_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_port",
     "query": "SELECT max(\"peak_of_transfer_mebibytes_per_sec\") AS \"Peak Transfer Rate\" FROM \"storage_port\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"port_name\"::tag =~ /^$worst_avg_xfer_port$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"port_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "peak_of_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Peak Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "port_name::tag", "operator": "=~", "value": "/^$worst_avg_xfer_port$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 155 },
   "options": {
    "content": "<hr style=\"height: 2px; background-color: #4acdeb\">"
   }
  },
  {
   "title": "Port Transfer Rate (Top $top_count)",
   "type": "gauge",
   "description": "Green < 200MB / Yellow 200MB-1000MB / Blue >1000MB",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_port_name($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "port_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_port",
     "query": "SELECT max(\"peak_of_transfer_mebibytes_per_sec\") AS \"Peak Transfer Rate\" FROM \"storage_port\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"port_name\"::tag =~ /^$worst_avg_xfer_port$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"port_name\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "peak_of_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Peak Transfer Rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "port_name::tag", "operator": "=~", "value": "/^$worst_avg_xfer_port$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 168 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Port IOPS (Top $top_count)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_port_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "port_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_port",
     "query": "SELECT max(\"peak_of_transfer_mebibytes_per_sec\") AS \"Peak Transfer Rate\" FROM \"storage_port\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"port_name\"::tag =~ /^$worst_avg_xfer_port$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"port_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "avg_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Peak IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "port_name::tag", "operator": "=~", "value": "/^$worst_avg_io_port$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 181 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  { "title": "Pools ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"sum_of_pool_physical_usage_in_percent\") AS \"Total Pool Usage\"\nFROM\n    (\n        SELECT\n            \"sum_of_pool_physical_usage_in_gibibyte\" / \"sum_of_pool_total_physical_capacity_in_gibibyte\" * 100 AS \"sum_of_pool_physical_usage_in_percent\"\n        FROM\n            \"storage\"\n        )\nWHERE\n        $timeFilter\n        AND \"instance_name\"::tag =~ /^$Storage$/\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Reduction Ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 184 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    last(\"Data Reduction Ratio\")\nFROM\n    (\n        SELECT\n           ( \"sum_of_pool_logical_usage_in_gibibyte\" + \"sum_of_pool_total_saving_capacity_in_gibibyte\" )/ \"sum_of_pool_logical_usage_in_gibibyte\" AS \"Data Reduction Ratio\"\n        FROM\n            \"storage\"\n        )\nWHERE\n        \"instance_name\"::tag =~ /^$Storage$/\nGROUP BY\n    \"instance_name\"::tag",
     "select": [
      [
       {
        "params": [
         "sum_of_pool_total_logical_capacity_in_gibibyte"
        ],
        "type": "field"
       }
      ],
      [
       {
        "params": [
         "sum_of_pool_physical_usage_in_gibibyte"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 191 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Pool Capacity",
   "type": "timeseries",
   "description": "Sum of capacity of the selected pools",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "alias": "$col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT\n    max(\"total_physical_total_capacity_in_gbytes\") as \"Phys. Total\",\n    max(\"total_subscription_capacity_in_gbytes\") as \"Subscription\",\n    max(\"total_physical_used_capacity_in_gbytes\") as \"Phys. Used\"\nFROM\n(\n        SELECT\n            sum(\"subscribed_capacity_in_gibibyte\") as \"total_subscription_capacity_in_gbytes\",\n            sum(\"physical_usage_in_gibibyte\") as \"total_physical_used_capacity_in_gbytes\",\n            sum(\"total_physical_capacity_in_gibibyte\") as \"total_physical_total_capacity_in_gbytes\"\n        FROM\n            \"storage_pool\"\n        WHERE\n            \"instance_name\" =~ /^$Storage$/\n            AND \"pool_display_name\" =~ /^$Pool$/\n        GROUP BY\n            \"instance_name\"\n    )\nWHERE\n    $timeFilter\nGROUP BY\n         \"instance_name\"::tag,\n         time($__interval)\nfill(none)",
     "select": [
      [
       {
        "params": [
         "sum_of_pool_total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_pool_subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_pool_physical_usage_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_pool_display_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT\n    last(\"physical_usage_in_percent\") AS \"Pool Usage\"\nFROM\n    (\n        SELECT\n            \"physical_usage_in_gibibyte\" / \"total_physical_capacity_in_gibibyte\" * 100 as \"physical_usage_in_percent\"\n        FROM\n            \"storage_pool\"\n        )\nWHERE\n    \"instance_name\"::tag =~ /^$Storage$/\n    AND \"pool_display_name\"::tag =~ /^$worst_usage_pool$/\n    AND $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag,\n    \"pool_display_name\"::tag\nfill(none)",
     "select": [
      [
       {
        "params": [
         "total_physical_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Total" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Subscription" ], "type": "alias" }
      ],
      [
       { "params": [ "physical_usage_in_gibibyte" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Phys. Used" ], "type": "alias" }
      ]
     ],
     "slimit": "100",
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$Pool$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 201 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": " IOPS (All Pools)",
   "type": "table",
   "description": "Average IOPS during the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_pool_display_name",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT mean(\"sum_of_total_io_per_sec\") AS \"Total\", mean(\"sum_of_read_io_per_sec\") AS \"Read\", mean(\"sum_of_write_io_per_sec\") AS \"Write\" FROM \"storage_pool\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"pool_display_name\"::tag =~ /^$worst_usage_pool$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"pool_display_name\"::tag",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool IOPS (Top $top_count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_pool_display_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "pool_display_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_pool",
     "query": "SELECT max(\"sum_of_total_io_per_sec\") AS \"Total\" FROM \"storage_pool\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"pool_display_name\"::tag =~ /^$worst_iops_pool$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"pool_display_name\"::tag fill(none)",
     "select": [
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "pool_display_name::tag", "operator": "=~", "value": "/^$worst_iops_pool$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 211 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  { "title": "Volumes ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 } },
  {
   "title": "IOPS (All Volumes)",
   "type": "table",
   "description": "Average IOPS during the selected time range",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT\n    mean(\"total_io_per_sec\") AS \"Total\",\n    mean(\"read_io_per_sec\") AS \"Read\",\n    mean(\"write_io_per_sec\") AS \"Write\"   \nFROM\n    (\n        SELECT\n            (\"read_io_per_sec\" + \"write_io_per_sec\") AS \"total_io_per_sec\", \n            \"read_io_per_sec\",\n            \"write_io_per_sec\"\n        FROM\n            \"storage_ldev\"\n        WHERE\n            \"instance_name\"::tag =~ /^$Storage$/\n    )\nWHERE\n    $timeFilter\nGROUP BY\n    \"instance_name\"::tag,\n    \"ldev_number\"::tag",
     "select": [
      [
       { "params": [ "read_io_per_sec" ], "type": "field" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_io_per_sec" ], "type": "field" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "title": "Selected Volume IOPS",
   "type": "timeseries",
   "description": "IOPS of the selected volumes",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_ldev_number ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT\n    max(\"total_io_per_sec\") AS \"Total\"\nFROM\n    (\n        SELECT\n            \"read_io_per_sec\" + \"write_io_per_sec\" AS \"total_io_per_sec\"\n        FROM\n            \"storage_ldev\"\n        WHERE\n            \"instance_name\"::tag =~ /^$Storage$/\n            AND \"ldev_number\"::tag =~ /^$Volume$/\n            AND $timeFilter\n        )\nWHERE $timeFilter\nGROUP BY\n    time($__interval),\n    \"instance_name\"::tag,\n    \"ldev_number\"::tag\nfill(none)",
     "select": [
      [
       { "params": [ "read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 224 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Response Time (All Volumes)",
   "type": "table",
   "description": "Average response time during the selected time range",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT mean(\"read_response_time_in_micro_sec\") AS \"Read\", mean(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"ldev_number\"::tag",
     "select": [
      [
       {
        "params": [
         "read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Selected Volume Response Time",
   "type": "timeseries",
   "description": "Response time of the selected volumes",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$col ($tag_ldev_number) ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT max(\"read_response_time_in_micro_sec\") AS \"Read\", max(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"ldev_number\"::tag =~ /^$Volume$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"ldev_number\"::tag fill(none)",
     "select": [
      [
       {
        "params": [
         "read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 237 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Block size (All Volumes)",
   "type": "table",
   "description": "Block size time during the selected time range",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT mean(\"read_response_time_in_micro_sec\") AS \"Read\", mean(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"ldev_number\"::tag",
     "select": [
      [
       { "params": [ "read_transfer_mebibytes_per_io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "title": "Selected Volume Block Size",
   "type": "timeseries",
   "description": "Block size of the selected volumes",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$col ($tag_ldev_number) ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "ldev_number::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_ldev",
     "query": "SELECT max(\"read_response_time_in_micro_sec\") AS \"Read\", max(\"write_response_time_in_micro_sec\") AS \"Write\" FROM \"storage_ldev\" WHERE (\"instance_name\"::tag =~ /^$Storage$/ AND \"ldev_number\"::tag =~ /^$Volume$/) AND $timeFilter GROUP BY time($__interval), \"instance_name\"::tag, \"ldev_number\"::tag fill(none)",
     "select": [
      [
       { "params": [ "read_transfer_mebibytes_per_io" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "write_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "ldev_number::tag", "operator": "=~", "value": "/^$Volume$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 250 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  { "title": "Host Groups ($Storage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 252 } },
  {
   "title": "Selected Host Max Read/Write Response",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_host_group_name $col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "max_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "max_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "host_group_name::tag", "operator": "=~", "value": "/^$Host_Group$/" }
     ]
    }
   ]
  },
  {
   "title": "All Hosts Max Response Time (Last)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 253 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "max_of_write_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Write Response (ms)" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "max_of_read_response_time_in_micro_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Read Response (ms)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 264 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Selected Host Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 266 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_host_group_name $col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "sum_of_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "host_group_name::tag", "operator": "=~", "value": "/^$Host_Group$/" }
     ]
    }
   ]
  },
  {
   "title": "All Hosts Transfer Rate (Last)",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 266 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "sum_of_write_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write (MB)" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_read_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read (MB)" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_total_transfer_mebibytes_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 277 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Selected Host IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_host_group_name $col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       { "params": [ "sum_of_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "host_group_name::tag", "operator": "=~", "value": "/^$Host_Group$/" }
     ]
    }
   ]
  },
  {
   "title": "All Hosts IOPS (Avg)",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 279 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       { "params": [ "sum_of_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Write IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Read IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_total_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 290 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Selected Host Seq/Random IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 292 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "alias": "$tag_host_group_name $col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       { "params": [ "sum_of_random_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rand Read" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_random_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Rand Write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Seq Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Seq Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "host_group_name::tag", "operator": "=~", "value": "/^$Host_Group$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 303 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "All Hosts Seq/Random IOPS (Avg)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 305 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       { "params": [ "sum_of_random_write_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Random Write IOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "sum_of_random_read_io_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Random Read IOPS" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_write_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Seq Write IOPS" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_sequential_read_io_per_sec"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Seq Read IOPS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 316 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "Selected Host Block Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "$tag_host_group_name $col ($tag_instance_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "avg_of_read_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_write_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" },
      { "condition": "AND", "key": "host_group_name::tag", "operator": "=~", "value": "/^$Host_Group$/" }
     ]
    }
   ]
  },
  {
   "title": "All Hosts Block Size (Avg)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 318 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_host_group",
     "select": [
      [
       {
        "params": [
         "avg_of_write_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1024" ], "type": "math" },
       { "params": [ "Write Block Size (K)" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "avg_of_read_transfer_mebibytes_per_io"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1024" ], "type": "math" },
       { "params": [ "Read Block Size (K)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 328 },
   "options": {
    "content": "<hr style=\"height: 6px; background-color: #b00000\">"
   }
  },
  {
   "title": "All Hosts Capacity Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 330 },
   "targets": [
    {
     "alias": "$tag_host_group_name ($tag_instance_name)",
     "groupBy": [
      { "params": [ "host_group_name::tag" ], "type": "tag" },
      { "params": [ "instance_name::tag" ], "type": "tag" }
     ],
     "measurement": "storage_pool_capacity_per_host_group",
     "select": [
      [
       {
        "params": [
         "sum_of_virtual_volume_subscribed_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" },
       { "params": [ "Subscribed (TB)" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "sum_of_virtual_volume_used_capacity_in_gibibyte"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" },
       { "params": [ "Used (TB)" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance_name::tag", "operator": "=~", "value": "/^$Storage$/" }
     ]
    }
   ]
  }
 ]
}